const opening=document.querySelector('#opening'),archive=document.querySelector('#archive'),modal=document.querySelector('#lightbox'),modalImg=document.querySelector('#lightbox-image'),modalCaption=document.querySelector('#lightbox-caption');
// Change these captions to make every sticky note personal.
const captions=['snake eyes, hypnotize','menace has been put to sleep','where it all started...','do you remember when you hated me?','look at how much cooler i look','going to be in our marriage picturebook','so cute','our baby is cursed','yuh!!!'];
const flourishField=document.querySelector('#flourish-field');
for(let i=0;i<58;i++){const leaf=document.createElement('i');leaf.className='flourish';leaf.style.cssText=`left:${(i*37+9)%97}%;top:${(i*71+13)%95}%;--size:${18+(i%7)*8}px;--turn:${(i*43)%360}deg;--fade:${.22+(i%4)*.07}`;flourishField.append(leaf)}
for(let i=0;i<20;i++){const mark=document.createElement('b'),type=['dot','ring','cross','dash'][i%4];mark.className=`explicit-mark ${type}`;mark.textContent=type==='cross'?'+':type==='dash'?'—':'';mark.style.cssText=`left:${(i*29+7)%96}%;top:${(i*53+11)%96}%;--mark-size:${8+(i%4)*4}px;--mark-rotate:${(i*31)%180}deg`;flourishField.append(mark)}
function reveal(){if(document.body.classList.contains('revealed'))return;document.body.classList.add('revealed');archive.setAttribute('aria-hidden','false')}opening.addEventListener('click',reveal);opening.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')reveal()});
document.querySelectorAll('.photo-note').forEach((note,index)=>{note.querySelector('p').textContent=captions[index];note.addEventListener('click',()=>{modalImg.src=note.querySelector('img').src;modalCaption.textContent=captions[index];modal.showModal()})});
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mouse-x',`${e.clientX}px`);document.documentElement.style.setProperty('--mouse-y',`${e.clientY}px`);document.querySelectorAll('.sticky-note').forEach(note=>{const b=note.getBoundingClientRect(),x=(e.clientX-b.left-b.width/2)/b.width,y=(e.clientY-b.top-b.height/2)/b.height;if(Math.abs(x)<1.4&&Math.abs(y)<1.4){note.style.setProperty('--hover-x',`${x*7}px`);note.style.setProperty('--hover-y',`${y*7}px`)}})});
document.querySelector('#close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.close()});
